DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INT GENERATED ALWAYS AS IDENTITY,
	USER_NAME VARCHAR(30),
	PASS VARCHAR(100)
);

INSERT INTO USERS(USER_NAME, PASS) VALUES
	('danghungvn2602', 'c0dingislife'),
	('nhutkha', '123456');