DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS NGUOI_DUNG (
	MA_SO VARCHAR(20) PRIMARY KEY,
	HO_TEN VARCHAR(45),
	SDT VARCHAR(11),
	EMAIL VARCHAR(45),
	MAT_KHAU VARCHAR(45),
	VAI_TRO INT NOT NULL
);

INSERT INTO NGUOI_DUNG(MA_SO, HO_TEN, SDT, EMAIL, MAT_KHAU, VAI_TRO) VALUES 
	(1, 'HUNG', '0123456789', 'hung@mail.com', '123456' , 1),
	(2, 'KHA', '0123456789', 'kha@mail.com', '123456' , 2);

CREATE TABLE IF NOT EXISTS PHONG_TRO (
	MA_SO VARCHAR(20) PRIMARY KEY,
	MO_TA VARCHAR(200),
	GIA_THUE INT
);

CREATE TABLE IF NOT EXISTS BAI_DANG (
	MA_SO VARCHAR(20) PRIMARY KEY,
	NGUOI_DANG CHAR(20),
	THOI_DIEM TIMESTAMP,
	DANH_GIA FLOAT,
	PHONG_TRO VARCHAR(20),
	FOREIGN KEY (NGUOI_DANG) REFERENCES NGUOI_DUNG(MA_SO),
	FOREIGN KEY (PHONG_TRO) REFERENCES PHONG_TRO(MA_SO)
);

CREATE TABLE IF NOT EXISTS HINH_ANH (
	MA_SO VARCHAR(20) PRIMARY KEY,
	PHONG_TRO VARCHAR(20),
	HINH_ANH VARCHAR(250),
	FOREIGN KEY (PHONG_TRO) REFERENCES PHONG_TRO(MA_SO)
);